name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - 'feature/**'
      - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: frabert/replace-string-action@v2
        with:
          pattern: 'refs/heads/feature/(\w+)'
          string: ${{ github.ref }}
          replace-with: '$1'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test -- ${{ steps.test.outputs.replaced }}.test.ts
        env:
          BASIC_LOGIN: ${{secrets.BASIC_LOGIN}}
          BASIC_PASSWORD: ${{secrets.BASIC_PASSWORD}}
          MONGO_DB_URL: ${{secrets.MONGO_DB_URL}}
          MONGO_DB_NAME: test
  Deploy:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: |
          prodRun="preview"
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="production"
          fi
          npx vercel pull --yes --environment=$prodRun --token=${VERCEL_TOKEN}
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
             prodRun=""
             if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
               prodRun="--prod"
             fi
             npx vercel build $prodRun --token=${VERCEL_TOKEN}
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi
          npx vercel deploy --prebuilt $prodRun --token=${VERCEL_TOKEN} -e BASIC_LOGIN=${BASIC_LOGIN} -e BASIC_PASSWORD=${BASIC_PASSWORD} -e PORT=5000  -e MONGO_DB_NAME=${MONGO_DB_NAME} -e MONGO_DB_URL=${MONGO_DB_URL}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          BASIC_LOGIN: ${{secrets.BASIC_LOGIN}}
          BASIC_PASSWORD: ${{secrets.BASIC_PASSWORD}}
          MONGO_DB_NAME: ${{secrets.MONGO_DB_NAME}}
          MONGO_DB_URL: ${{secrets.MONGO_DB_URL}}

