name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - 'feature/**'
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information (Feature)
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Pull Vercel Environment Information (Main)
        if: startsWith(github.ref, 'refs/heads/main')
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts (Feature)
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts (Main)
        if: startsWith(github.ref, 'refs/heads/main')
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel (Feature)
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} -e API_ROUTE=${{ github.head_ref || github.ref_name }} -e PORT=5000
      - name: Deploy Project Artifacts to Vercel (Main)
        if: startsWith(github.ref, 'refs/heads/main')
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} -e API_ROUTE=${{ github.head_ref || github.ref_name }} -e PORT=5000
