name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - 'feature/**'
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: |
          prodRun="preview"
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="production"
          fi
          npx vercel pull --yes --environment=$prodRun --token=${VERCEL_TOKEN}
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
             prodRun=""
             if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
               prodRun="--prod"
             fi
             npx vercel build $prodRun --token=${VERCEL_TOKEN}
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi
          npx vercel deploy --prebuilt $prodRun --token=${VERCEL_TOKEN}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

